// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// updateSuffStat
NumericMatrix updateSuffStat(NumericMatrix xx_xy, NumericVector y, NumericMatrix x_less_ones);
RcppExport SEXP NYCTaxi_updateSuffStat(SEXP xx_xySEXP, SEXP ySEXP, SEXP x_less_onesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type xx_xy(xx_xySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_less_ones(x_less_onesSEXP);
    __result = Rcpp::wrap(updateSuffStat(xx_xy, y, x_less_ones));
    return __result;
END_RCPP
}
