# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to update the sufficient statistics of linear regression based on a bulk of data
#' 
#' The sufficient statistics of the linear regression is recorded as a p-by-(p+1) matrix which is the row concatenation of x^Hx and x^Hy where p is the number of predictors (including constant 1).
#' @param xx_xy a p-by-(p+1) matrix, [1:p, 1:p] represents the current value of x^Hx and [p+1, 1:p] represents the current value of x^Hy
#' @param y a n-by-1 vector, the bulk of observatons
#' @param x_less_ones a n-by-(p-1) matrix, the bulk of predictors excluding 1
#' @return the updated sufficient statistic xx_xy
#' @export
updateSuffStat <- function(xx_xy, y, x_less_ones) {
    .Call('NYCTaxi_updateSuffStat', PACKAGE = 'NYCTaxi', xx_xy, y, x_less_ones)
}

